config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # devise_scopeを追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :tasks do
    collection do
      get 'tasks_for_kids'
      get 'rewards'
      get 'manual', to: 'pages#under_construction'
      get 'badge', to: 'pages#under_construction'
      get 'parents_dashboard'
      post 'exchange_reward'
      post 'reset_task'
    end

    member do
      put 'choose'
      put 'mark_complete'
      put 'cancel_task'
    end
  end

  resources :parents, only: [] do
    collection do
      get 'new_child', to: 'parents#new_child'
      post 'create_child', to: 'parents#create_child'
      get 'dashboard'
      delete 'destroy_child/:id', to: 'parents#destroy_child', as: 'destroy_child'
    end
  end

  get 'role_selection', to: 'role_selection#index' # 役割選択ページのルーティングを変更

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener_web' if Rails.env.development?
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :status, inclusion: { in: %w[未着手 着手中 完了 交換済み], message: '%<value>s は有効な状態ではありません' }

  after_initialize :set_default_status

  private

  def set_default_status
    self.status ||= '未着手'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :ensure_child_belongs_to_current_user, only: [:rewards]

  def index
    @tasks = if params[:child_id]
               Task.where(user_id: params[:child_id], status: '着手中').page(params[:page]).per(5)
             else
               Task.page(params[:page]).per(5)
             end
  end

  def choose
    task = Task.find(params[:id])
    if task.update(user_id: params[:child_id], status: '着手中')
      redirect_to tasks_path(child_id: params[:child_id]), notice: 'おてつだいがんばってね！'
    else
      puts task.errors.full_messages
      redirect_to tasks_path(child_id: params[:child_id]), alert: '何らかのエラーが発生しました。'
    end
  end

  def mark_complete
    @task = Task.find(params[:id])
    @task.update(status: '完了')

    child = User.find(@task.user_id)
    child.points ||= 0
    reward_points = @task.reward || 0
    child.points += reward_points

    if child.save(validate: false)
      Rails.logger.debug("Child's points updated successfully to: #{child.points}")
    else
      Rails.logger.error("Error updating child's points: #{child.errors.full_messages.join(', ')}")
    end

    redirect_to tasks_path(child_id: child.id), notice: 'おてつだいありがとう！！'
  end

  def tasks_for_kids
    @tasks = Task.where(user_id: current_user.id).where.not(status: '着手中')
  end

  def rewards
    child_id = params[:child_id] || current_user.children.first&.id

    unless child_id
      redirect_to root_path, alert: '関連する子供が存在しません。'
      return
    end

    @completed_tasks = Task.where(user_id: child_id, status: '完了')
    @total_reward = @completed_tasks.sum(:reward)
    @exchanged_items = Task.where(user_id: child_id, status: '交換済み')
  end

  def show
    @hide_sidebar = true
  end

  def new
    @task = Task.new
    @hide_sidebar = true
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    if @task.save
      redirect_to dashboard_parents_path, notice: 'お手伝いが正常に作成されました'
    else
      flash.now[:alert] = @task.errors.full_messages.join(', ')
      @hide_sidebar = true
      render :new
    end
  end

  def cancel_task
    @task = Task.find(params[:id])
    @task.update(status: '未着手', user_id: current_user.id)
    redirect_back(fallback_location: tasks_path, notice: 'おてつだいをやめました。')
  end

  def edit
    @hide_sidebar = true

    return if @task.user_id == current_user.id

    redirect_to tasks_path, alert: 'アクセス権限がありません'
    nil
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'お手伝いが正常に更新されました'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to dashboard_parents_path, notice: 'おてつだいが正常に削除されました'
  end

  def exchange_reward
    item = params[:item]
    required_points = params[:points].to_i
    child = User.find(params[:child_id])
    child_points = child.points || 0

    if child_points >= required_points
      new_points = child_points - required_points
      child.update_columns(points: new_points)
      Task.create(name: item, status: '交換済み', user_id: child.id, description: "#{item}とこうかんしました。")

      redirect_to rewards_tasks_path(child_id: child.id), notice: "#{item}をこうかんしました！"
    else
      redirect_to rewards_tasks_path(child_id: child.id), alert: 'ポイントがたりません。'
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :status, :due_on, :reward)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: @task, html: { class: 'needs-validation', novalidate: '' }) do |f| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :name, "タスク名", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", required: "", placeholder: "タスク名を入力" %>
        <div class="invalid-feedback">
          タスク名は必須です。
        </div>
      </div>

      <div class="form-group col-md-6">
        <%= f.label :description, "詳細", class: "form-label" %>
        <%= f.text_area :description, class: "form-control", rows: 5, required: "", placeholder: "タスクの詳細を入力" %>
        <div class="invalid-feedback">
          詳細は必須です。
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :due_on, "期限", class: "form-label" %>
        <%= f.select :due_on, [["今日", Date.today], ["明日", Date.today + 1.day], ["来週", Date.today + 7.days]], {}, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= f.label :reward, "報酬", class: "form-label" %>
        <%= f.select :reward, (100..5000).step(100), {}, class: "form-control" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "登録", class: "btn btn-primary btn-lg mr-2" %>
      <%= link_to 'キャンセル', dashboard_parents_path, class: "btn btn-secondary btn-lg" %>

    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div style="background-color: desired-color; min-height: 100vh;">
<div class="container mt-5">
  <h1 class="mb-4"><%= @task.name %>を編集</h1>

  <%= render 'form' %>

  </div>
</div>
</div>

app/views/tasks/index.html.erb
<div style="background-color: desired-color; min-height: 100vh;">
<div class="container mt-5">

<% if user_signed_in? && !@is_guardian_page && !@is_role_selection && !@hide_sidebar %>
  <!-- サイドメニュー -->
<nav class="side-menu bg-primary p-3 rounded d-flex flex-column justify-content-center">
  <ul class="list-group">
    <%= link_to tasks_for_kids_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-info mb-2 rounded text-center py-3 card">
        <i class="fas fa-question-circle text-white d-block mb-1"></i> てつだう
      </li>
    <% end %>
<br>
    <%= link_to tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-success mb-2 rounded text-center py-3 card">
        <i class="fas fa-tasks text-white d-block mb-1"></i> やってる
      </li>
    <% end %>
<br>
    <%= link_to rewards_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-warning mb-2 rounded text-center py-3 card">
        <i class="fas fa-gift text-white d-block mb-1"></i> ごほうび
      </li>
    <% end %>
  </ul>
</nav>

  
<% end %>

  <h1 class="display-4 text-center mb-4">やってるおてつだい</h1>

  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">なまえ</th>
        <th class="text-center">ママパパからのおねがい</th>
        <th class="text-center"> いつまでに？</th>
        <th class="text-center">ポイント</th>
        <th class="text-center">😀</th>
        <th class="text-center">😭</th>
      </tr>
    </thead>
    <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td class="text-center"><%= task.name %></td>
      <td class="text-center"><%= task.description %></td>
      <td class="text-center"><%= task.due_on %></td>
      <td class="text-center"><%= task.reward %>ポイント</td>
      <td class="text-center">
        <%= button_to "おわった", mark_complete_task_path(task), method: :put, class: "btn btn-success btn-sm" %>
      </td>
      <td class="text-center">
        <%= button_to "やめる", cancel_task_task_path(task), method: :put, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
  <% end %>
</tbody>

  </table>
</div>

app/views/tasks/new.html.erb
<div style="background-color: desired-color; min-height: 100vh;">
  <div class="container mt-5">
    <h1 class="mb-4">お手伝いの登録</h1>
      <%= render 'form' %>
    </div>
  </div>

app/views/tasks/rewards.html.erb
<div style="background-color: desired-color; min-height: 100vh;">
<div class="container mt-5">
  <div class="header-section d-flex justify-content-between align-items-center">
    <h1 class="display-4 mb-4">🎁ごほうび🎁</h1>
    <span class="points-badge">もってるポイント&nbsp;&nbsp;&nbsp;<%= User.find(params[:child_id]).points %>P</span>
  </div>

  <h2 class="mb-3">おわったおてつだい</h2>
  
<% if user_signed_in? && !@is_guardian_page && !@is_role_selection && !@hide_sidebar %>
  <!-- サイドメニュー -->
<nav class="side-menu bg-primary p-3 rounded d-flex flex-column justify-content-center">
  <ul class="list-group">
    <%= link_to tasks_for_kids_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-info mb-2 rounded text-center py-3 card">
        <i class="fas fa-question-circle text-white d-block mb-1"></i> てつだう
      </li>
    <% end %>
<br>
    <%= link_to tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-success mb-2 rounded text-center py-3 card">
        <i class="fas fa-tasks text-white d-block mb-1"></i> やってる
      </li>
    <% end %>
<br>
    <%= link_to rewards_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-warning mb-2 rounded text-center py-3 card">
        <i class="fas fa-gift text-white d-block mb-1"></i> ごほうび
      </li>
    <% end %>
  </ul>
</nav>

  
<% end %>

  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">おてつだい</th>
        <th class="text-center">いつおわったの？</th>
        <th class="text-center">もらったポイント</th>
      </tr>
    </thead>
    <!-- ... 以下のコード ... -->

    <tbody>
      <% @completed_tasks.each do |task| %>
        <tr>
          <td class="text-center"><%= task.name %></td>
          <td class="text-center"><%= task.due_on %></td>
          <td class="text-center"><%= task.reward %>ポイント</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="mt-5 mb-3">ごほうびえらんでね</h2>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">ごほうび</th>
        <th class="text-center">ひつようなポイント</th>
        <th class="text-center">こうかん</th>
      </tr>
    </thead>
    <tbody>

      <tr>
        <td class="text-center">おやつ</td>
        <td class="text-center">100ポイント</td>
        <td class="text-center"><%= button_to 'こうかん', exchange_reward_tasks_path(item: 'おやつ', points: 100, child_id: params[:child_id]), method: :post, class: "btn btn-primary btn-sm" %></td>
      </tr>
      <tr>
        <td class="text-center">300円</td>
        <td class="text-center">3000ポイント</td>
        <td class="text-center"><%= button_to 'こうかん', exchange_reward_tasks_path(item: '300円', points: 3000, child_id: params[:child_id]), method: :post, class: "btn btn-primary btn-sm" %></td>
      </tr>
      <tr>
        <td class="text-center">500円</td>
        <td class="text-center">5000ポイント</td>
        <td class="text-center"><%= button_to 'こうかん', exchange_reward_tasks_path(item: '500円', points: 5000, child_id: params[:child_id]), method: :post, class: "btn btn-primary btn-sm" %></td>
      </tr>
      <!-- 他のアイテムも同様に追加可能 -->
    </tbody>
  </table>

  <h2 class="mt-5 mb-3">もらったごほうび</h2>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">ごほうび</th>
        <th class="text-center">いつこうかんしたか？</th>
        <th class="text-center">ママパパからコメント</th>
      </tr>
    </thead>
    <tbody>
      <% @exchanged_items.each do |item| %>
        <tr>
          <td class="text-center"><%= item.name %></td>
          <td class="text-center"><%= item.created_at.strftime('%Y-%m-%d (%a)') %></td>
          <td class="text-center"><%= item.description %></td> <!-- 交換の詳細情報を表示 -->
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4"><%= @task.name %></h1>

  <div class="card mb-4">
    <div class="card-body">
      <p class="lead"><strong>詳細:</strong> <%= @task.description %></p>
      <p class="lead"><strong>状態:</strong> <%= @task.status %></p>
      <p class="lead"><strong>期限:</strong> <%= @task.due_on %></p>
      <p class="lead"><strong>報酬:</strong> <%= @task.reward %>ポイント</p>
    </div>
  </div>

  <div class="d-flex">
    <%= link_to '編集', edit_task_path(@task), class: "btn btn-warning" %>
    <%= link_to '削除', @task, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>
    <%= link_to '戻る', dashboard_parents_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/tasks/tasks_for_kids.html.erb
<div style="background-color: desired-color; min-height: 100vh;">

<div class="container mt-5">

<% if user_signed_in? && !@is_guardian_page && !@is_role_selection && !@hide_sidebar %>
  <!-- サイドメニュー -->
<nav class="side-menu bg-primary p-3 rounded d-flex flex-column justify-content-center">
  <ul class="list-group">
    <%= link_to tasks_for_kids_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-info mb-2 rounded text-center py-3 card">
        <i class="fas fa-question-circle text-white d-block mb-1"></i> てつだう
      </li>
    <% end %>
<br>
    <%= link_to tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-success mb-2 rounded text-center py-3 card">
        <i class="fas fa-tasks text-white d-block mb-1"></i> やってる
      </li>
    <% end %>
<br>
    <%= link_to rewards_tasks_path(child_id: params[:child_id]), class: "text-white d-block" do %>
      <li class="list-group-item bg-warning mb-2 rounded text-center py-3 card">
        <i class="fas fa-gift text-white d-block mb-1"></i> ごほうび
      </li>
    <% end %>
  </ul>
</nav>

  
<% end %>

  <h1 class="display-4 text-center mb-4">おてつだいえらんでね</h1>

  <% if @tasks && @tasks.any? %>
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th class="text-center">おてつだい</th>
          <th class="text-center">ママパパからのおねがい</th>
          <th class="text-center">もらえるポイント</th>
          <th class="text-center">アクション</th> 
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td class="text-center"><%= task.name %></td>
            <td class="text-center"><%= task.description %></td>
            <td class="text-center"><%= task.reward %>ポイント</td>
            <td class="text-center">
              <%= button_to "これをする！", choose_task_path(task, child_id: params[:child_id]), method: :put, class: "btn btn-primary" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info" role="alert">
      お手伝いのタスクはありません。
    </div>
  <% end %>
</div>
</div>