config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # devise_scopeを追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :tasks do
    collection do
      get 'tasks_for_kids'
      get 'rewards'
      get 'manual', to: 'pages#under_construction'
      get 'badge', to: 'pages#under_construction'
      get 'parents_dashboard'
      post 'exchange_reward'
      post 'reset_task'
    end

    member do
      put 'choose'
      put 'mark_complete'
      put 'cancel_task'
    end
  end

  resources :parents, only: [] do
    collection do
      get 'new_child', to: 'parents#new_child'
      post 'create_child', to: 'parents#create_child'
      get 'dashboard'
      delete 'destroy_child/:id', to: 'parents#destroy_child', as: 'destroy_child'
    end
  end

  get 'role_selection', to: 'role_selection#index' # 役割選択ページのルーティングを変更

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener_web' if Rails.env.development?
end

app/controllers/role_selection_controller.rb
class RoleSelectionController < ApplicationController
  def index
    @is_role_selection = true
  end
end

app/helpers/role_selection_helper.rb
module RoleSelectionHelper
end

app/views/role_selection/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <!-- その他のヘッド要素 -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.x.x/dist/vue.js"></script>
</head>
<body>
<div id="app" style="background-color: desired-color; min-height: 100vh;">
    <!-- ポップアップウィンドウのコンポーネント -->
    <div v-if="showPopup" class="popup">
        <img src="/images/animal_zou.png" alt="ゾウのイラスト" style="width:500px; height:auto;">
        <h2>「やるぞう」へようこそ！</h2>
        <p>おてつだいをはじめるまえに</p>
        <p>あなたが「ママパパ」か「こども」かおしえてね。</p>
        <button @click="closePopup">どちらかえらぶ🍎</button>
    </div>

    <div class="container mt-5">
        <h2 class="display5 text-center mb-4" style="color: #333;">あなたはどっちですか？</h2>

        <div class="d-flex flex-column align-items-center">
            <%= link_to "パパママ", dashboard_parents_path, class: "btn btn-outline-dark btn-lg mb-3" %>

            <% current_user.children.each do |child| %>
                <%= link_to "#{child.name}として進む", tasks_path(child_id: child.id), class: "btn btn-outline-secondary btn-lg mb-3" %>
            <% end %>
        </div>
    </div>
</div>

<script>
    new Vue({
        el: '#app',
        data: {
            showPopup: true
        },
        methods: {
            closePopup: function() {
                this.showPopup = false;
            }
        }
    });
</script>
</body>
</html>