config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # devise_scopeを追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end

  resources :tasks do
    collection do
      get 'tasks_for_kids'
      get 'rewards'
      get 'manual', to: 'pages#under_construction'
      get 'badge', to: 'pages#under_construction'
      get 'parents_dashboard'
      post 'exchange_reward'
      post 'reset_task'
    end

    member do
      put 'choose'
      put 'mark_complete'
      put 'cancel_task'
    end
  end

  resources :parents, only: [] do
    collection do
      get 'new_child', to: 'parents#new_child'
      post 'create_child', to: 'parents#create_child'
      get 'dashboard'
      delete 'destroy_child/:id', to: 'parents#destroy_child', as: 'destroy_child'
    end
  end

  get 'role_selection', to: 'role_selection#index' # 役割選択ページのルーティングを変更

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener_web' if Rails.env.development?
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_guardian_flag

  def new_child
    @child = User.new
  end

  def create_child
    @child = User.new(child_params)
    @child.role = 'kid'
    @child.email = SecureRandom.uuid + '@example.com'
    @child.password = SecureRandom.hex(8)
    if @child.save
      FamilyLink.create(parent: current_user, child: @child)
      redirect_to dashboard_parents_path, notice: '子どもを追加しました'
    else
      flash.now[:alert] = '名前を入力して下さい。'
      render :new_child
    end
  end

  def destroy_child
    child = User.find(params[:id])
    child.destroy
    redirect_to dashboard_parents_path, notice: "#{child.name} を削除しました"
  end

  def dashboard
    @children = current_user.children

    # 1. パラメータからフィルタリングやソートの値を取得
    name_filter = params[:name_filter]
    status_filter = params[:status_filter]
    sort_option = params[:sort]

    # 2. 取得した値に基づいて、@tasks のクエリを修正
    tasks_query = Task.where(user_id: @children + [current_user.id])

    tasks_query = tasks_query.where.not(status: '交換済み')

    # 名前でのフィルタリング
    tasks_query = tasks_query.where('name LIKE ?', "%#{name_filter}%") if name_filter.present?

    # 状態でのフィルタリング
    tasks_query = tasks_query.where(status: status_filter) unless status_filter == '全て' || status_filter.blank?

    # ソート
    case sort_option
    when '期限昇順'
      tasks_query = tasks_query.order(due_on: :asc)
    when '期限降順'
      tasks_query = tasks_query.order(due_on: :desc)
    when '報酬昇順'
      tasks_query = tasks_query.order(reward: :asc)
    when '報酬降順'
      tasks_query = tasks_query.order(reward: :desc)
    end

    @tasks = tasks_query.page(params[:page]).per(5)

    @children_with_tasks = @children.map do |child|
      tasks = Task.where(user_id: child.id, status: %w[着手中 完了])
      completed_tasks = tasks.where(status: '完了')
      total_reward = completed_tasks.sum(:reward)
      {
        child: child,
        tasks: tasks,
        total_reward: total_reward
      }
    end
  end

  private

  def child_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_guardian_flag
    @is_guardian_page = true
  end
end

app/views/parents/dashboard.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4">保護者ダッシュボード</h1>

  <div class="display-4 text-center mb-5">
    <%= link_to "お手伝いを追加", new_task_path, class: "btn btn-primary mr-5 " %>
    <%= link_to "子どもを追加", new_child_parents_path, class: "btn btn-success mr-5" %>
    <%= link_to "アカウント設定", edit_user_registration_path, class: "btn btn-info mr-5" %>
  </div>

  <h2 class="mb-3">子ども一覧</h2>
  <ul class="list-group mb-4">
    <% @children.each do |child| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to child.name, tasks_path(child_id: child.id), class: "mr-2" %>
        <%= link_to "削除", destroy_child_parents_path(child.id), method: :delete, data: { confirm: "#{child.name}を削除しますか？" }, class: "btn btn-danger btn-sm" %>
      </li>
    <% end %>
  </ul>

  <% @children_with_tasks.each do |data| %>
  <div class="card">
    <div class="header-section" style="display: flex; align-items: center; justify-content: space-between;">
      <h3 class="mb-2" style="margin-right: 10px;"><%= data[:child].name %>のお手伝い</h3>
      <span class="points-badge">所持<%= data[:child].points %>ポイント</span>
    </div>
    
    <ul class="list-group mb-3">
      <% data[:tasks].each do |task| %>
        <li class="list-group-item" data-status="<%= task.status %>">
          <%= task.name %> - <%= task.status %> - <%= task.reward %>ポイント
        </li>
      <% end %>
    </ul>


    <h4>ごほうび</h4>
<ul class="list-group mb-4">
  <% exchanged_tasks = Task.where(user_id: data[:child].id, status: "交換済み") %>
  <% exchanged_tasks.each do |task| %>
    <li class="list-group-item" data-status="交換済み">
      <%= task.description %> - <%= task.created_at.strftime('%Y-%m-%d (%a)') %>
    </li>
  <% end %>
</ul>
</div>
<% end %>

  <div class="mb-4">
    <%= form_tag(dashboard_parents_path, method: :get, class: "form-inline") do %>
      <div class="form-group mr-2">
        <%= label_tag :name_filter, "お手伝い名:", class: "mr-1" %>
        <%= text_field_tag :name_filter, params[:name_filter], class: "form-control mr-2" %>
      </div>
      <div class="form-group mr-2">
        <%= label_tag :status_filter, "状態:", class: "mr-1" %>
        <%= select_tag :status_filter, options_for_select(["全て", "未着手", "着手中", "完了"], params[:status_filter]), class: "form-control" %>
      </div>
      <div class="form-group mr-2">
        <%= label_tag :sort, "並べ替え:", class: "mr-1" %>
        <%= select_tag :sort, options_for_select(["期限昇順", "期限降順", "報酬昇順", "報酬降順"], params[:sort]), class: "form-control" %>
      </div>
      <%= submit_tag "フィルタリング&ソート", class: "btn btn-secondary" %>
    <% end %>
  </div>

  <h2 class="mb-3">お手伝い一覧</h2>
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">お手伝い名</th>
        <th class="text-center">詳細</th>
        <th class="text-center">状態</th>
        <th class="text-center">期限日</th>
        <th class="text-center">報酬</th>
        <th class="text-center">編集</th>
        <th class="text-center">削除</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td class="text-center"><%= task.name %></td>
          <td class="text-center"><%= task.description %></td>
          <td class="text-center"><%= task.status %></td>
          <td class="text-center"><%= task.due_on %></td>
          <td class="text-center"><%= task.reward %>P</td>
          <td class="text-center"><%= link_to '編集', edit_task_path(task), class: "btn btn-warning btn-sm" %></td>
          <td class="text-center"><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <%= paginate @tasks %>

  <h2 class="mb-3">交換できる報酬</h2>
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th class="text-center">アイテム名</th>
        <th class="text-center">必要ポイント</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-center">おかし</td>
        <td class="text-center">100ポイント</td>
      </tr>
      <tr>
        <td class="text-center">300円</td>
        <td class="text-center">3000ポイント</td>
      </tr>
      <tr>
        <td class="text-center">500円</td>
        <td class="text-center">5000ポイント</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/parents/new_child.html.erb
<div style="background-color: desired-color; min-height: 100vh;">
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4">子どもを追加</h1>

  <%= form_for User.new, url: create_child_parents_path, html: { class: 'needs-validation', novalidate: '' } do |f| %>

    <div class="form-group">
      <%= f.label :name, "子どもの名前", class: "form-label" %>
      <%= f.text_field :name, class: "form-control", required: "", placeholder: "子どもの名前を入力" %>
      <div class="invalid-feedback">
        このフィールドは必須です。
      </div>
    </div>

    <div class="actions">
    <%= f.submit "登録", class: "btn btn-primary btn-lg mr-2" %>
    <%= link_to 'キャンセル', dashboard_parents_path, class: "btn btn-secondary btn-lg" %>
</div>

  <% end %>
</div>